apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: x5m29yqqh-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/x5m29yqqh-dotnet-basic-gitops